name: Capture Screenshots

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      
      - run: pnpm install --frozen-lockfile
      
      - run: pnpm run build
      
      - run: pnpm start
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'feat: add screenshot'
          file_pattern: 'screenshots/**/*.png'
